### ISSUE TITLE
Feature request: search in activity selection

### ISSUE THREAD

**Issue by Jamesits** [joserebelo/Lolistat#4]
It's hard to find things through a long activity listview. Could you please add a search function on that? 

Also, consider coloring items whose settings are different from default.

**Comment by joserebelo** [comment]
Added search to the activity list (979a3d50fc567865f5a75f88f7b51caf8b1b2510), will be in the next release.

About the settings that are different from default, I may try to add some kind of indicator in the future, the preferences also need to be reorganized into groups as more are added.
